CREATE TABLE document
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    file_path           VARCHAR(255)                            NOT NULL,
    file_size_in_bytes  BIGINT,
    batch_id            VARCHAR(255),
    uploader_profile_id UUID                                    NOT NULL,
    signed              BOOLEAN                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_document PRIMARY KEY (id)
);

CREATE TABLE email_notification
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id UUID                                    NOT NULL,
    subject    VARCHAR(255)                            NOT NULL,
    body       OID                                     NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    sent_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_email_notification PRIMARY KEY (id)
);

CREATE TABLE esign
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    signer_profile_id UUID                                    NOT NULL,
    document_id       BIGINT                                  NOT NULL,
    signature         BYTEA                                   NOT NULL,
    signed_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_esign PRIMARY KEY (id)
);

CREATE TABLE log_entry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id UUID                                    NOT NULL,
    action     VARCHAR(255)                            NOT NULL,
    details    TEXT,
    logged_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_log_entry PRIMARY KEY (id)
);

CREATE TABLE organization
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    owner_id   UUID                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_organization PRIMARY KEY (id)
);

CREATE TABLE profile
(
    id             UUID                        NOT NULL,
    firstname      VARCHAR(255)                NOT NULL,
    lastname       VARCHAR(255)                NOT NULL,
    email          VARCHAR(255)                NOT NULL,
    password       VARCHAR(255)                NOT NULL,
    email_verified BOOLEAN                     NOT NULL,
    public_key     OID,
    org_id         BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE profile_to_role
(
    profile_id UUID   NOT NULL,
    role_id    BIGINT NOT NULL,
    CONSTRAINT pk_profile_to_role PRIMARY KEY (profile_id, role_id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE organization
    ADD CONSTRAINT uc_organization_name UNIQUE (name);

ALTER TABLE profile
    ADD CONSTRAINT uc_profile_email UNIQUE (email);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_UPLOADER_PROFILE FOREIGN KEY (uploader_profile_id) REFERENCES profile (id);

ALTER TABLE email_notification
    ADD CONSTRAINT FK_EMAIL_NOTIFICATION_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id);

ALTER TABLE esign
    ADD CONSTRAINT FK_ESIGN_ON_DOCUMENT FOREIGN KEY (document_id) REFERENCES document (id);

ALTER TABLE esign
    ADD CONSTRAINT FK_ESIGN_ON_SIGNER_PROFILE FOREIGN KEY (signer_profile_id) REFERENCES profile (id);

ALTER TABLE log_entry
    ADD CONSTRAINT FK_LOG_ENTRY_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id);

ALTER TABLE organization
    ADD CONSTRAINT FK_ORGANIZATION_ON_OWNER FOREIGN KEY (owner_id) REFERENCES profile (id);

ALTER TABLE profile
    ADD CONSTRAINT FK_PROFILE_ON_ORG FOREIGN KEY (org_id) REFERENCES organization (id);

ALTER TABLE profile_to_role
    ADD CONSTRAINT fk_protorol_on_profile FOREIGN KEY (profile_id) REFERENCES profile (id);

ALTER TABLE profile_to_role
    ADD CONSTRAINT fk_protorol_on_role FOREIGN KEY (role_id) REFERENCES role (id);