-- Migration for DocumentType and Application entity
create table application (id bigint generated by default as identity, created_at timestamp(6) with time zone not null, status varchar(255) not null check (status in ('PENDING','ACCEPTED','REJECTED')), updated_at timestamp(6) with time zone not null, profile_id uuid not null, document_id bigint, organization_id bigint not null, primary key (id));
alter table if exists document add column document_type varchar(255) check (document_type in ('CV','OTHER'));
alter table if exists esign alter column signature set data type BYTEA;
alter table if exists log_entry alter column details set data type TEXT;
alter table if exists application drop constraint if exists UKpc8e0lhi0ocdrfuy1ccmesivx;
alter table if exists application add constraint UKpc8e0lhi0ocdrfuy1ccmesivx unique (profile_id, organization_id);
alter table if exists application drop constraint if exists UKbloensui33jwqt4t7e8k2wpb4;
alter table if exists application add constraint UKbloensui33jwqt4t7e8k2wpb4 unique (document_id);
alter table if exists application add constraint FK2bteh044rjpejdb58vaq6rrr3 foreign key (profile_id) references profile;
alter table if exists application add constraint FKi95jn4ckqwei6b60ul2i4guqa foreign key (document_id) references document;
alter table if exists application add constraint FKr7dxqnwu3rgug7du538brkedh foreign key (organization_id) references organization;
