CREATE TABLE email_verification_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    token VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_verification_user FOREIGN KEY (user_id) REFERENCES profile(id) ON DELETE CASCADE
);

-- Add index for faster token lookup
CREATE INDEX idx_email_verification_token ON email_verification_token(token);
CREATE INDEX idx_email_verification_user_id ON email_verification_token(user_id);

ALTER TABLE profile ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
