
    create table document (
        signed boolean not null,
        size integer,
        id bigint generated by default as identity,
        profile_id uuid not null,
        batch varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table email_notifications (
        id bigint generated by default as identity,
        profile_id uuid not null,
        link varchar(255),
        title varchar(255) not null,
        text oid not null,
        primary key (id)
    );

    create table esign (
        id bigint generated by default as identity,
        signature BYTEA not null,
        primary key (id)
    );

    create table logs (
        datetime timestamp(6) not null,
        id bigint generated by default as identity,
        profile_id uuid not null,
        action varchar(255) not null,
        primary key (id)
    );

    create table organization (
        no_employees integer,
        id bigint generated by default as identity,
        owner_id uuid not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table profile (
        esign_id bigint unique,
        org_id bigint,
        id uuid not null,
        email varchar(255) not null,
        firstname varchar(255) not null,
        lastname varchar(255) not null,
        primary key (id),
        unique (email)
    );

    create table profile_to_role (
        role_id bigint not null,
        profile_id uuid not null,
        primary key (role_id, profile_id)
    );

    create table role (
        id bigint generated by default as identity,
        name varchar(20) not null unique check (name in ('ADMIN','HR','USER')),
        primary key (id)
    );

    alter table if exists document 
       add constraint FKg7fj71dcduh2ey134fuv31gax 
       foreign key (profile_id) 
       references profile;

    alter table if exists email_notifications 
       add constraint FKc6jw7hva3b58paywfa69st2ir 
       foreign key (profile_id) 
       references profile;

    alter table if exists logs 
       add constraint FK9kur8kwdhae4u2w9mq6t8qh3r 
       foreign key (profile_id) 
       references profile;

    alter table if exists organization 
       add constraint FKmodnfh3lk0miih5j5og8yf516 
       foreign key (owner_id) 
       references profile;

    alter table if exists profile 
       add constraint FKal4gh5dobtcshyax0oxfqi2i 
       foreign key (esign_id) 
       references esign;

    alter table if exists profile 
       add constraint FK82ykp219cmgmsyj46df6xhbpn 
       foreign key (org_id) 
       references organization;

    alter table if exists profile_to_role 
       add constraint FK67y06jluomeimt44wbpx6dkvn 
       foreign key (role_id) 
       references role;

    alter table if exists profile_to_role 
       add constraint FKsjkdygbew8y4i7btexkam4awh 
       foreign key (profile_id) 
       references profile;

    create table document (
        signed boolean not null,
        created_at timestamp(6) with time zone not null,
        file_size_in_bytes bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        uploader_profile_id uuid not null,
        batch_id varchar(255),
        file_path varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table email_notification (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        sent_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        profile_id uuid not null,
        status varchar(255) not null,
        subject varchar(255) not null,
        body oid not null,
        primary key (id)
    );

    create table esign (
        document_id bigint not null,
        id bigint generated by default as identity,
        signed_at timestamp(6) with time zone not null,
        signer_profile_id uuid not null,
        signature BYTEA not null,
        primary key (id)
    );

    create table log_entry (
        id bigint generated by default as identity,
        logged_at timestamp(6) with time zone not null,
        profile_id uuid not null,
        action varchar(255) not null,
        details TEXT,
        primary key (id)
    );

    create table organization (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        owner_id uuid not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table profile (
        email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        org_id bigint,
        updated_at timestamp(6) with time zone not null,
        id uuid not null,
        email varchar(255) not null unique,
        firstname varchar(255) not null,
        lastname varchar(255) not null,
        password varchar(255) not null,
        public_key oid,
        primary key (id)
    );

    create table profile_to_role (
        role_id bigint not null,
        profile_id uuid not null,
        primary key (role_id, profile_id)
    );

    create table role (
        id bigint generated by default as identity,
        name varchar(20) not null unique check (name in ('ADMIN','HR','USER')),
        primary key (id)
    );

    alter table if exists document 
       add constraint FK582ed4iuimlmiw47wdhesim4w 
       foreign key (uploader_profile_id) 
       references profile;

    alter table if exists email_notification 
       add constraint FKphnu2evngfxl30cobkir5e1xs 
       foreign key (profile_id) 
       references profile;

    alter table if exists esign 
       add constraint FKppcivau7ln1ooxkrb2el287l1 
       foreign key (document_id) 
       references document;

    alter table if exists esign 
       add constraint FKcigm9qp79xjsbcerh6yh06dpu 
       foreign key (signer_profile_id) 
       references profile;

    alter table if exists log_entry 
       add constraint FKf8gv433edf7yk3mgy5xd0jbe2 
       foreign key (profile_id) 
       references profile;

    alter table if exists organization 
       add constraint FKmodnfh3lk0miih5j5og8yf516 
       foreign key (owner_id) 
       references profile;

    alter table if exists profile 
       add constraint FK82ykp219cmgmsyj46df6xhbpn 
       foreign key (org_id) 
       references organization;

    alter table if exists profile_to_role 
       add constraint FK67y06jluomeimt44wbpx6dkvn 
       foreign key (role_id) 
       references role;

    alter table if exists profile_to_role 
       add constraint FKsjkdygbew8y4i7btexkam4awh 
       foreign key (profile_id) 
       references profile;
